"""
Part C: Interview Ready
Q1 - Conceptual answer demonstrated with code
Q2 - analyze_csv() function
Q3 - Debug the 3 bugs
"""

import pandas as pd
import numpy as np

print("=" * 55)
print("         PART C: INTERVIEW READY")
print("=" * 55)

# -----------------------------------------------
# Q1: .loc[] vs .iloc[] difference
# -----------------------------------------------
print("\n--- Q1: .loc[] vs .iloc[] ---")

# When index is 0,1,2,3,4
df_numeric = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "score": [85, 90, 78, 92, 88]
})

print("\nDataFrame with numeric index (0,1,2,3,4):")
print(df_numeric)

print("\ndf.loc[0:3]  -- label-based, INCLUSIVE of 3:")
print(df_numeric.loc[0:3])

print("\ndf.iloc[0:3] -- position-based, EXCLUSIVE of 3:")
print(df_numeric.iloc[0:3])

# When index is 'a','b','c','d','e'
df_str = df_numeric.copy()
df_str.index = ['a', 'b', 'c', 'd', 'e']

print("\nDataFrame with string index ('a','b','c','d','e'):")
print(df_str)

print("\ndf.loc['a':'c']  -- label-based, includes 'c':")
print(df_str.loc['a':'c'])

print("\ndf.iloc[0:3]     -- still position-based, excludes position 3:")
print(df_str.iloc[0:3])

print("""
Key difference summary:
  .loc[]  → uses LABELS (row names/index values), end is INCLUSIVE
  .iloc[] → uses INTEGER POSITIONS (0-based), end is EXCLUSIVE

When index is 0,1,2,3,4:
  df.loc[0:3]  → returns rows 0,1,2,3  (4 rows - inclusive)
  df.iloc[0:3] → returns rows 0,1,2    (3 rows - exclusive)

When index is 'a','b','c','d','e':
  df.loc['a':'c']  → returns rows a,b,c (label-inclusive)
  df.iloc[0:3]     → still returns rows at positions 0,1,2 = a,b,c
""")

# -----------------------------------------------
# Q2: analyze_csv() function
# -----------------------------------------------
print("\n--- Q2: analyze_csv() Function ---")

def analyze_csv(filepath):
    """
    Loads a CSV, prints the 'First 5 Minutes' checklist,
    and returns a summary dictionary.
    """
    df = pd.read_csv(filepath)

    print("\n=== First 5 Minutes Checklist ===")
    print(f"Shape        : {df.shape}")
    print(f"Columns      : {list(df.columns)}")
    print(f"Data Types   :\n{df.dtypes}")
    print(f"Missing vals :\n{df.isnull().sum()}")
    print(f"Head:\n{df.head()}")
    print(f"Describe:\n{df.describe()}")

    numeric_cols = list(df.select_dtypes(include=[np.number]).columns)
    categorical_cols = list(df.select_dtypes(include=["object", "category"]).columns)
    null_counts = df.isnull().sum().to_dict()
    memory_mb = round(df.memory_usage(deep=True).sum() / (1024 ** 2), 4)

    result = {
        "num_rows": df.shape[0],
        "num_cols": df.shape[1],
        "numeric_cols": numeric_cols,
        "categorical_cols": categorical_cols,
        "null_counts": null_counts,
        "memory_mb": memory_mb
    }

    print("\n=== Summary Dict ===")
    for key, val in result.items():
        print(f"  {key}: {val}")

    return result


# Test it with budget_products.csv (generated by Part A)
print("\nTesting analyze_csv() on budget_products.csv:")
try:
    result = analyze_csv("budget_products.csv")
except FileNotFoundError:
    print("Run product_analyzer.py first to generate budget_products.csv")

# -----------------------------------------------
# Q3: Debug the 3 bugs
# -----------------------------------------------
print("\n--- Q3: Debugging 3 Bugs ---")

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age":  [25, 30, 35],
    "salary": [50000, 60000, 70000]
})

# Bug 1 Fix: use & (bitwise) instead of 'and' (Python keyword)
# Original (buggy): df[df["age"] > 25 and df["salary"] > 55000]
# Fix: use & with parentheses around each condition
high_earners = df[(df["age"] > 25) & (df["salary"] > 55000)]
print(f"\nBug 1 Fixed - high_earners:\n{high_earners}")
print("  Explanation: Use '&' for element-wise AND on Series, not 'and'.")
print("  Also wrap each condition in parentheses due to operator precedence.")

# Bug 2 Fix: use .loc[] for assignment instead of chained indexing
# Original (buggy): df["age"][0] = 26  -> raises SettingWithCopyWarning
# Fix: use df.loc[index, column]
df.loc[0, "age"] = 26
print(f"\nBug 2 Fixed - df.loc[0, 'age'] updated to: {df.loc[0, 'age']}")
print("  Explanation: Chained indexing df['col'][idx] may modify a copy.")
print("  Use df.loc[row_label, col_label] for safe in-place assignment.")

# Bug 3 Fix: iloc[0:3] actually returns 3 rows (positions 0,1,2) - that IS correct
# The bug is the comment expecting 3 rows from [0:2]
# iloc[0:2] gives rows at index 0 and 1 only (2 rows), not 3
first_three = df.iloc[0:3]   # corrected slice to get 3 rows
print(f"\nBug 3 Fixed - first_three rows: {len(first_three)}")
print(first_three)
print("  Explanation: df.iloc[0:2] gives only 2 rows (positions 0 and 1).")
print("  iloc slicing is exclusive on the end, so use iloc[0:3] for 3 rows.")

print("\nDone!")
